# Generated by Django 4.2.4 on 2023-08-18 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_pype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_pypes', to='catalogue.producttype'),
        ),
        migrations.AlterField(
            model_name='productattributevalue',
            name='value',
            field=models.CharField(max_length=48),
        ),
    ]
