# Generated by Django 4.2.4 on 2023-08-18 22:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_producttype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttype',
            name='modifies_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
