# Generated by Django 4.2.4 on 2023-08-19 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_alter_brand_parent_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_pype',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products_types', to='catalogue.producttype'),
        ),
    ]
