# Generated by Django 4.2.4 on 2023-08-21 23:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_product_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
