# Generated by Django 4.2.4 on 2023-09-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='is_active',
        ),
    ]
