# Generated by Django 4.2.4 on 2023-09-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_transaction_type_userscore_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': [('Has_score_permission', 'User has score permission')]},
        ),
    ]
