# Generated by Django 4.2.4 on 2023-09-10 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_userscore_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscore',
            options={'permissions': [('has_score_permission', 'has score permission')]},
        ),
    ]
